### ISSUE TITLE
Communication issue between file-source in 'ref' mode and s3-sink

### ISSUE THREAD

**Issue by scdfdev20** [spring-cloud/stream-applications#240]
Hi

I need to upload a file into S3 from a file-source in 'ref' mode like this :

> s3file_stream=file-source: file --filename-regex='(.*(\.xml)$)' --directory=/tmp --mode=ref | s3-sink: s3 --endpoint-url=http://[YOUR_S3_HOST] --path-style-access=true --bucket=[YOUR BUCKET] --cloud.aws.credentials.accessKey=[YOUR_ACCESS_KEY] --cloud.aws.credentials.secretKey=[YOUR_SECRET_KEY] --cloud.aws.region.static=us-east-1 --cloud.aws.stack.auto=false

s3-sink throws this exception :

> Caused by: **java.lang.IllegalArgumentException: Unsupported payload type: [class java.lang.String]. The only supported payloads for the upload request are java.io.File, java.io.InputStream, byte[] and PutObjectRequest**.
> 	at org.springframework.integration.aws.outbound.S3MessageHandler.upload(S3MessageHandler.java:375) ~[spring-integration-aws-2.3.4.RELEASE.jar!/:na]
> 	at org.springframework.integration.aws.outbound.S3MessageHandler.handleRequestMessage(S3MessageHandler.java:277) ~[spring-integration-aws-2.3.4.RELEASE.jar!/:na]
> 	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:136) ~[spring-integration-core-5.5.4.jar!/:5.5.4]
> 	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:56) ~[spring-integration-core-5.5.4.jar!/:5.5.4]
> 	... 43 common frames omitted

It seems that s3-sink does not unterstand that it receives a file path (send by file-source with 'ref' mode), and not a content (in 'String' format) to put into a file.

**Message infos :**
- **"headers"**:[{"key":"b3","stringValue":"185ed08fb276cc13-9532e1c011357543-0"},{"key":"nativeHeaders","stringValue":"{\"b3\":[\"185ed08fb276cc13-9532e1c011357543-0\"]}"},{"key":"file_name","stringValue":"test.xml"},{"key":"file_originalFile","stringValue":"\"/tmp/test.xml\""},{"key":"contentType","stringValue":"application/json"},{"key":"file_relativePath","stringValue":"test.xml"},{"key":"spring_json_header_types","stringValue":"{\"b3\":\"java.lang.String\",\"nativeHeaders\":\"org.springframework.util.LinkedMultiValueMap\",\"file_name\":\"java.lang.String\",\"file_originalFile\":\"java.io.File\",\"contentType\":\"java.lang.String\",\"file_relativePath\":\"java.lang.String\"}"}]
- **"value"**:"\"/tmp/test.xml\""

**Versions :**
- Version of Dataflow server = 2.9.2
- Version of Skipper Server = 2.8.2
- Version of file-source and s3-sink = 3.1.1
- Open Java 17.0.1
- Kafka 3.0.0

**Comment by artembilan** [comment]
I believe your problem is exactly what we discuss over here: https://github.com/spring-cloud/stream-applications/issues/200.

So, I'm closing this one as a duplication of that one.
According mentioned fixes in Spring Cloud Function the next version of Stream Applications should bring your solution back to work.
