### ISSUE TITLE
aggregator-processor (3.2.0) does not start up

### ISSUE THREAD

**Issue by making** [spring-cloud/stream-applications#248]
```
java -jar aggregator-processor-kafka-3.2.0.jar ....
```

does not start and eats up the cpu. nothing output

```
docker run --rm springcloudstream/aggregator-processor-kafka:3.2.0
```

is the same.

I managed to capture the error log on k8s platform although it eats up the cpu as well

```
demo-aggr-aggregator-v1-8455d64597-qwspz demo-aggr-aggregator-v1 16:09:51.347 [main] ERROR org.springframework.boot.SpringApplication - Application run failed
demo-aggr-aggregator-v1-8455d64597-qwspz demo-aggr-aggregator-v1 java.lang.IllegalArgumentException: [/proc/self/task/1/cwd/proc/self/task/1/cwd/proc/self/task/1/cwd/proc/self/task/1/cwd/proc/self/task/1/cwd/proc/self/task/1/cwd/proc/self/task/1/cwd/proc/self/task/1/cwd/proc/self/task/1/cwd/proc/self/task/1/cwd/proc/self/task/1/cwd/proc/self/task/1/cwd/proc/self/task/1/cwd/proc/self/task/1/cwd/proc/self/task/1/cwd/proc/self/task/1/cwd/proc/self/task/1/cwd/proc/self/task/1/cwd/proc/self/task/1/cwd/proc/self/task/1/cwd/sys/kernel/slab/shmem_inode_cache/cgroup/shmem_inode_cache(1450:cloud-final.service)] is not a valid directory
demo-aggr-aggregator-v1-8455d64597-qwspz demo-aggr-aggregator-v1 	at org.springframework.util.Assert.isTrue(Assert.java:121)
demo-aggr-aggregator-v1-8455d64597-qwspz demo-aggr-aggregator-v1 	at org.springframework.geode.boot.autoconfigure.SslAutoConfiguration.assertDirectory(SslAutoConfiguration.java:248)
demo-aggr-aggregator-v1-8455d64597-qwspz demo-aggr-aggregator-v1 	at org.springframework.geode.boot.autoconfigure.SslAutoConfiguration.locateKeyStoreInFileSystem(SslAutoConfiguration.java:213)
demo-aggr-aggregator-v1-8455d64597-qwspz demo-aggr-aggregator-v1 	at org.springframework.geode.boot.autoconfigure.SslAutoConfiguration.locateKeyStoreInFileSystem(SslAutoConfiguration.java:219)
demo-aggr-aggregator-v1-8455d64597-qwspz demo-aggr-aggregator-v1 	at org.springframework.geode.boot.autoconfigure.SslAutoConfiguration.locateKeyStoreInFileSystem(SslAutoConfiguration.java:219)
demo-aggr-aggregator-v1-8455d64597-qwspz demo-aggr-aggregator-v1 	at org.springframework.geode.boot.autoconfigure.SslAutoConfiguration.locateKeyStoreInFileSystem(SslAutoConfiguration.java:219)
demo-aggr-aggregator-v1-8455d64597-qwspz demo-aggr-aggregator-v1 	at org.springframework.geode.boot.autoconfigure.SslAutoConfiguration.locateKeyStoreInFileSystem(SslAutoConfiguration.java:219)
demo-aggr-aggregator-v1-8455d64597-qwspz demo-aggr-aggregator-v1 	at org.springframework.geode.boot.autoconfigure.SslAutoConfiguration.locateKeyStoreInFileSystem(SslAutoConfiguration.java:219)
demo-aggr-aggregator-v1-8455d64597-qwspz demo-aggr-aggregator-v1 	at org.springframework.geode.boot.autoconfigure.SslAutoConfiguration.locateKeyStoreInFileSystem(SslAutoConfiguration.java:219)
demo-aggr-aggregator-v1-8455d64597-qwspz demo-aggr-aggregator-v1 	at org.springframework.geode.boot.autoconfigure.SslAutoConfiguration.locateKeyStoreInFileSystem(SslAutoConfiguration.java:219)
demo-aggr-aggregator-v1-8455d64597-qwspz demo-aggr-aggregator-v1 	at org.springframework.geode.boot.autoconfigure.SslAutoConfiguration.locateKeyStoreInFileSystem(SslAutoConfiguration.java:219)
demo-aggr-aggregator-v1-8455d64597-qwspz demo-aggr-aggregator-v1 	at org.springframework.geode.boot.autoconfigure.SslAutoConfiguration.locateKeyStoreInFileSystem(SslAutoConfiguration.java:219)
```

looks like geode module is activated even if geode is not chosen as a message store

**Comment by artembilan** [comment]
OK. Looks like there is `org.springframework.geode.boot.autoconfigure.SslAutoConfiguration.SslEnvironmentPostProcessor`, which is not disable and tries to find key store in our dirs.
It just passes locally because we have only valid dirs in our env.
Looks like with Docker it is not always OK.
Anyway such a `SslEnvironmentPostProcessor` is conditional:
```
private boolean isEnabled(Environment environment) {
	return environment.getProperty(SECURITY_SSL_ENVIRONMENT_POST_PROCESSOR_ENABLED_PROPERTY,
				Boolean.class, true);
}
```
So, we need to consider to set this option to `false` to not let a Geode SSL try to be pre-configured.

**Comment by artembilan** [comment]
The logic in that recursive function is like this:
```
	private static Optional<File> locateKeyStoreInFileSystem(File directory, String keystoreFilename) {

		assertDirectory(directory);

		for (File file : nullSafeListFiles(directory)) {

			if (isDirectory(file)) {

				Optional<File> theFile = locateKeyStoreInFileSystem(file, keystoreFilename);

				if (theFile.isPresent()) {
					return theFile;
				}
				else {
					continue;
				}
			}

			if (file.getName().equals(keystoreFilename)) {
				return Optional.of(file);
			}
		}

		return Optional.empty();
	}
```

How it can pass `if (isDirectory(file)) {` when it then fails on the recursive call immediately on that `assertDirectory(directory);`?
This one looks like this:
```
private static void assertDirectory(File path) {
		Assert.isTrue(isDirectory(path), String.format("[%s] is not a valid directory", path));
	}
```
where the same `isDirectory()` called again...

That's kinda out of our project scope: just for your info if you'd like to consult with Spring Data Geode team to figure out what is wrong with your dir to scan for key and trust stores.

The fix for exclusion is on its way.

**Comment by CEDDM** [comment]
Hi ! It seems that I have the same issue in 3.2.1. Has this correction been packaged ?
In which release train ?

**Comment by onobc** [comment]
HI @CEDDM ,

This should be available in the `3.2.1` aggregator-processor in the `2021.1.2` release.

Can you provide the steps to reproduce what you are seeing? 

Thanks

**Comment by CEDDM** [comment]
Thanks @onobc 
I tried `3.0.1`, `3.1.1` and `3.2.1` versions with no luck. I think all v3 aggregator have this issue.
I can't provide anything because the app just freezes at startup and consumes all cpu. There is nothing in the log
I switched to aggregator `2021.1.x` and it works fine

**Comment by onobc** [comment]
Oh, interesting @CEDDM . 

Can you tell me how you are invoking it though? I ask because when I ran it via `java -jar` everything worked as expected. The original poster was using `java -jar` and/or `docker run`. I just want to make sure that I can repro and see the same thing you see. 

Thanks

**Comment by CEDDM** [comment]
You're right, I use it with `SCDF 2.9.6` and Kafka in Kubernetes so maybe there are some differences.
Thanks for looking into this

**Comment by onobc** [comment]
You are welcome @CEDDM . Out of curiosity, what K8S env are you running on?

**Comment by CEDDM** [comment]
I use `microk8s 1.25` env for development
