### ISSUE TITLE
Not able to configure metadatastore for s3 source kafka binder app

### ISSUE THREAD

**Issue by Noushath** [spring-cloud/stream-applications#266]
We are currently using https://mvnrepository.com/artifact/org.springframework.cloud.stream.app/s3-source-kafka/3.2.0 for our spring cloud dataflow pipeline. We are trying to use the metadata store as zookeper with below configs

app.s3.metadata.store.type=zookeeper
app.s3.metadata.store.zookeeper.connect-string=zookeeper:2181

```
java.lang.IllegalStateException: Error processing condition on org.springframework.cloud.fn.common.metadata.store.MetadataStoreAutoConfiguration$Zookeeper.curatorFramework
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:60) ~[spring-boot-autoconfigure-2.6.3.jar!/:2.6.3]
	at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:108) ~[spring-context-5.3.15.jar!/:5.3.15]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForBeanMethod(ConfigurationClassBeanDefinitionReader.java:193) ~[spring-context-5.3.15.jar!/:5.3.15]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:153) ~[spring-context-5.3.15.jar!/:5.3.15]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:129) ~[spring-context-5.3.15.jar!/:5.3.15]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:343) ~[spring-context-5.3.15.jar!/:5.3.15]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:247) ~[spring-context-5.3.15.jar!/:5.3.15]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:311) ~[spring-context-5.3.15.jar!/:5.3.15]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:112) ~[spring-context-5.3.15.jar!/:5.3.15]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:746) ~[spring-context-5.3.15.jar!/:5.3.15]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:564) ~[spring-context-5.3.15.jar!/:5.3.15]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[spring-boot-2.6.3.jar!/:2.6.3]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732) ~[spring-boot-2.6.3.jar!/:2.6.3]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:414) ~[spring-boot-2.6.3.jar!/:2.6.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:302) ~[spring-boot-2.6.3.jar!/:2.6.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303) ~[spring-boot-2.6.3.jar!/:2.6.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292) ~[spring-boot-2.6.3.jar!/:2.6.3]
	at org.springframework.cloud.stream.app.s3.source.kafka.S3SourceKafkaApplication.main(S3SourceKafkaApplication.java:29) ~[classes!/:3.2.0]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[s3-source-kafka-3.2.0.jar:3.2.0]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[s3-source-kafka-3.2.0.jar:3.2.0]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[s3-source-kafka-3.2.0.jar:3.2.0]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[s3-source-kafka-3.2.0.jar:3.2.0]
Caused by: java.lang.IllegalStateException: @ConditionalOnMissingBean did not specify a bean using type, name or annotation and the attempt to deduce the bean's type failed
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition$Spec.validate(OnBeanCondition.java:487) ~[spring-boot-autoconfigure-2.6.3.jar!/:2.6.3]
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition$Spec.<init>(OnBeanCondition.java:436) ~[spring-boot-autoconfigure-2.6.3.jar!/:2.6.3]
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getMatchOutcome(OnBeanCondition.java:142) ~[spring-boot-autoconfigure-2.6.3.jar!/:2.6.3]
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:47) ~[spring-boot-autoconfigure-2.6.3.jar!/:2.6.3]
	... 25 common frames omitted
Caused by: org.springframework.boot.autoconfigure.condition.OnBeanCondition$BeanTypeDeductionException: Failed to deduce bean type for org.springframework.cloud.fn.common.metadata.store.MetadataStoreAutoConfiguration$Zookeeper.curatorFramework
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition$Spec.deducedBeanTypeForBeanMethod(OnBeanCondition.java:517) ~[spring-boot-autoconfigure-2.6.3.jar!/:2.6.3]
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition$Spec.deducedBeanType(OnBeanCondition.java:506) ~[spring-boot-autoconfigure-2.6.3.jar!/:2.6.3]
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition$Spec.<init>(OnBeanCondition.java:429) ~[spring-boot-autoconfigure-2.6.3.jar!/:2.6.3]
	... 27 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.apache.curator.framework.CuratorFramework
	at java.base/java.net.URLClassLoader.findClass(Unknown Source) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source) ~[na:na]
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151) ~[s3-source-kafka-3.2.0.jar:3.2.0]
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source) ~[na:na]
	at java.base/java.lang.Class.forName0(Native Method) ~[na:na]
	at java.base/java.lang.Class.forName(Unknown Source) ~[na:na]
	at org.springframework.boot.autoconfigure.condition.FilteringSpringBootCondition.resolve(FilteringSpringBootCondition.java:108) ~[spring-boot-autoconfigure-2.6.3.jar!/:2.6.3]
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition$Spec.getReturnType(OnBeanCondition.java:525) ~[spring-boot-autoconfigure-2.6.3.jar!/:2.6.3]
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition$Spec.deducedBeanTypeForBeanMethod(OnBeanCondition.java:513) ~[spring-boot-autoconfigure-2.6.3.jar!/:2.6.3]
	... 29 common frames omitted
```
Request guidance on what we are missing here? looks like some autoconfiguration property is getting missed to tell the zookeeper related beans to be initialized.

Also the above mentioned jar has a vulnerability is there any PRs in pipeline for the fix.

**Comment by artembilan** [comment]
Your exception is just lead to this fact:
```
Caused by: java.lang.ClassNotFoundException: org.apache.curator.framework.CuratorFramework
```

See documentation for the `MetadataStore` configuration in this stream applications: https://github.com/spring-cloud/stream-applications/tree/main/functions/common/metadata-store-common.

The Zookeeper part is like this:
> The `ZookeeperMetadataStore` requires this dependency for auto-configuration:

```
<dependency>
    <groupId>org.springframework.integration</groupId>
    <artifactId>spring-integration-zookeeper</artifactId>
</dependency>
```

So, to make it working you need to add that dependency into this `s3-source-kafka`.
See docs how to do that: https://docs.spring.io/stream-applications/docs/2021.1.2-SNAPSHOT/reference/html/#_patching_pre_built_applications

Not sure what you are talking about with a "vulnerability".

**Comment by artembilan** [comment]
The `s3-source` does not do any web data binding. So, that's false positive that such a vulnerability is pointed over there. 
The only fact that this project doesn't use the latest Spring Framework dependency and that's it.
It is going to be covered in the next release in the end of May.

**Comment by onobc** [comment]
@Noushath based on the above comments it sounds like this is resolved. Thanks.

**Comment by Noushath** [comment]
https://docs.spring.io/stream-applications/docs/2021.1.2-SNAPSHOT/reference/html/#_patching_pre_built_applications

what would be the best way to maintain such patched applications as mentioned in above link.
