### ISSUE TITLE
Investigate errors logged by Kafka Client during SCDF acceptance tests

### ISSUE THREAD

**Issue by corneil** [spring-cloud/stream-applications#308]
When running the SCDF ATs, the server-side contains Kafka errors. This is preventing failFast handling from working in the ATs. While we can code around that, we really want to make sure that the errors in the log are expected and not indicative of some other underlying issue. 

Execption occurs just after `log-sink` has read messages.

```
2022-06-15 18:53:56.067 WOODCHUCK-1 ERROR 1 --- [container-0-C-1] o.a.k.c.c.internals.ConsumerCoordinator  : [Consumer clientId=consumer-partitioning-test-2, groupId=partitioning-test] Offset commit failed on partition partitioning-test.splitter-1 at offset 20: The coordinator is not aware of this member.
2022-06-15 18:53:56.067 WOODCHUCK-1  INFO 1 --- [container-0-C-1] o.a.k.c.c.internals.ConsumerCoordinator  : [Consumer clientId=consumer-partitioning-test-2, groupId=partitioning-test] OffsetCommit failed with Generation{generationId=-1, memberId='', protocol='null'}: The coordinator is not aware of this member.
2022-06-15 18:53:56.068 WOODCHUCK-1  INFO 1 --- [container-0-C-1] o.a.k.c.c.internals.ConsumerCoordinator  : [Consumer clientId=consumer-partitioning-test-2, groupId=partitioning-test] Resetting generation due to: encountered UNKNOWN_MEMBER_ID from OFFSET_COMMIT response
2022-06-15 18:53:56.068 WOODCHUCK-1  INFO 1 --- [container-0-C-1] o.a.k.c.c.internals.ConsumerCoordinator  : [Consumer clientId=consumer-partitioning-test-2, groupId=partitioning-test] Request joining group due to: encountered UNKNOWN_MEMBER_ID from OFFSET_COMMIT response
2022-06-15 18:53:56.068 WOODCHUCK-1 ERROR 1 --- [container-0-C-1] o.s.k.l.KafkaMessageListenerContainer    : Consumer exception
	java.lang.IllegalStateException: This error handler cannot process 'org.apache.kafka.clients.consumer.CommitFailedException's; no record information is available
		at org.springframework.kafka.listener.DefaultErrorHandler.handleOtherException(DefaultErrorHandler.java:155) ~[spring-kafka-2.8.6.jar:2.8.6]
		at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.handleConsumerException(KafkaMessageListenerContainer.java:1791) ~[spring-kafka-2.8.6.jar:2.8.6]
		at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:1298) ~[spring-kafka-2.8.6.jar:2.8.6]
		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:na]
		at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
		at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
```

**Comment by corneil** [comment]
Discussion with Kafka Stream App experts indicated that these types of error messages are normal.
