### ISSUE TITLE
JDBC Sink doesn't support a timestamp input column

### ISSUE THREAD

**Issue by estigma88** [spring-cloud/stream-applications#324]
**Version**
jdbc sink 3.2.0

**Description**

Seems like the JDBC Sink doesn't support a timestamp input column.

We created a simple stream using SCDF as follows:
```
:jdbcSinkTest > jdbc --spring.datasource.username=postgres --spring.datasource.url=<url> --columns=created_at:createdAt --table-name=testtable --spring.datasource.password=<password>
```

There, we have as columns the created_at, which is a timespan in the database. We publish a message to the stream as follows:
```
{
	"createdAt": "2022-09-19T18:54:11.179891856"
}
```

When the sink tries to insert the message in the database, we got the following:

```
Caused by: org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [INSERT INTO report.fixture_stats(provider, provider_resource_id, pipeline_id, state_response, state, stats_response, connected, bytes_in_rate, frame_rate, keyframe_interval, height, height_status, width, width_status, svq_time, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]; nested exception is org.postgresql.util.PSQLException: ERROR: column "created_at" is of type timestamp with time zone but expression is of type character varying
Hint: You will need to rewrite or cast the expression.
Position: 315
at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:239) ~[spring-jdbc-5.3.15.jar:5.3.15]
at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:70) ~[spring-jdbc-5.3.15.jar:5.3.15]
at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1541) ~[spring-jdbc-5.3.15.jar:5.3.15]
at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:667) ~[spring-jdbc-5.3.15.jar:5.3.15]
at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:960) ~[spring-jdbc-5.3.15.jar:5.3.15]
at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:981) ~[spring-jdbc-5.3.15.jar:5.3.15]
```

**Clues**
It seems like the sink cannot convert the input to the right Java objects to pass them as parameters to the Postgres JDBC; therefore, the JDBC treats any inputs as String.

We tried to use something like SpEL to convert the input to an object the JDBC can understand, as follows:

```
--columns=created_at::T(java.time.LocalDateTime).parse(createdAt)
```

But we got the following error:

```
Could not find value for column 'created_at': EL1008E: Property or field 'java' cannot be found on object of type 'org.springframework.integration.support.MutableMessage'
```

[Checking the source code](https://github.com/spring-cloud/stream-applications/blob/1c50531c13c156dbc04919b77443b5dbec891307/functions/consumer/jdbc-consumer/src/main/java/org/springframework/cloud/fn/consumer/jdbc/JdbcConsumerConfiguration.java#L98), seems like the SpEL configuration inside the jdbc consumer [can only access the payload of the message](https://github.com/spring-cloud/stream-applications/blob/1c50531c13c156dbc04919b77443b5dbec891307/functions/consumer/jdbc-consumer/src/main/java/org/springframework/cloud/fn/consumer/jdbc/JdbcConsumerConfiguration.java#L267). If the SpEL configuration can be extended to any SpEl, we might be able to access static classes, and therefore, `T(java.time.LocalDateTime).parse(createdAt)` could work.

Any idea if this is already supported somehow?

**Comment by corneil** [comment]
Please try using: `--columns=created_at:T(java.time.LocalDateTime).parse(payload.createdAt)`

**Comment by estigma88** [comment]
It works, missing the `payload.` prefix

**Comment by corneil** [comment]
@estigma88 thanks for your prompt response.
