### ISSUE TITLE
Aggregator function failures 

### ISSUE THREAD

**Issue by onobc** [spring-cloud/stream-applications#373]
Aggregator Function tests disabled

- org.springframework.cloud.fn.aggregator.DefaultAggregatorTests
- org.springframework.cloud.fn.aggregator.CustomPropsAndMongoMessageStoreAggregatorTests
- org.springframework.cloud.fn.aggregator.JdbcMessageStoreAggregatorTests 

```
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.cloud.fn.aggregator.CustomPropsAndMongoMessageStoreAggregatorTests': Unsatisfied dependency expressed through field 'aggregatingMessageHandler': No qualifying bean of type 'org.springframework.integration.aggregator.AggregatingMessageHandler' available: expected single matching bean but found 2: aggregator,aggregator.serviceActivator.handler

	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:744)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:724)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:127)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:483)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1401)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireBeanProperties(AbstractAutowireCapableBeanFactory.java:397)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:136)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:94)
	at

```

**Comment by artembilan** [comment]
This is what I said in the call about bugs in Spring Integration. 😅
Will into this tomorrow .
